module.exports = {
    scheds: [
        { "title" : "1h",
          "list" : "516d72f773de5c8854000002",
          "start" : 1366081200, "end" : 1366084800,
          "allDay" : false,
          "event" : null,
          "_id" : 1366127401812 },
        { "title" : "1h",
          "list" : "516d72f773de5c8854000002",
          "start" : 1366084800, "end" : 1366088400,
          "allDay" : false,
          "event" : null,
          "_id" : 1366127410838 },
        { "title" : "1h",
          "list" : "516d72f773de5c8854000002",
          "start" : 1366088400, "end" : 1366092000,
          "allDay" : false,
          "event" : null,
          "_id" : 1366127412837 },
        { "title" : "1h",
          "list" : "516d72f773de5c8854000002",
          "start" : 1366092000, "end" : 1366095600,
          "allDay" : false,
          "event" : null,
          "_id" : 1366127414877 },
    ],
    lists: [
        {
            "published" : false,
            "collection" : [
                {
                    "ffmpegversion" : "1.2",
                    "title" : "",
                    "artist" : "",
                    "album" : "",
                    "track" : "",
                    "date" : "",
                    "durationraw" : "00:30:00.00",
                    "durationsec" : 1800,
                    "synched" : true,
                    "video" : {
                        "container" : "mov",
                        "bitrate" : 143,
                        "codec" : "mpeg4",
                        "resolution" : {
                            "w" : 672,
                            "h" : 504 },
                        "resolutionSquare" : {
                            "w" : 672,
                            "h" : 504
                        },
                        "rotate" : 0,
                        "fps" : 25,
                        "stream" : 0,
                        "aspectString" : "4:3",
                        "aspect" : 1.3333333333333333,
                        "pixelString" : "1:1",
                        "pixel" : 1
                    },
                    "audio" : {
                        "codec" : "",
                        "bitrate" : 0,
                        "sample_rate" : 0,
                        "stream" : 0 },
                    "file" : "./videos/SMPTE_Color_Bars_04.mp4",
                    "stat" : {
                        "dev" : 2053,
                        "mode" : 33204,
                        "nlink" : 1,
                        "uid" : 1000,
                        "gid" : 1000,
                        "rdev" : 0,
                        "blksize" : 4096,
                        "ino" : 3527,
                        "size" : 32325338,
                        "blocks" : 63144,
                        "atime" : "2013-04-16T15:36:10.000Z",
                        "mtime" : "2013-04-16T15:42:31.000Z",
                        "ctime" : "2013-04-16T15:42:31.000Z",
                        "name" : "SMPTE_Color_Bars_04.mp4",
                        "type" : "file" },
                    "checksum" : "ce96533228445a761ebadb396adbf053",
                    "name" : "",
                    "template" : "mediaview",
                    "notes" : "",
                    "trim" : {
                        "timein" : 0,
                        "timeout" : 0 },
                    "overlay" : [ ],
                    "starts" : 0,
                    "ends" : 0 },
                {
                    "ffmpegversion" : "1.2",
                    "title" : "",
                    "artist" : "",
                    "album" : "",
                    "track" : "",
                    "date" : "",
                    "durationraw" : "00:30:00.00",
                    "durationsec" : 1800,
                    "synched" : true,
                    "video" : {
                        "container" : "mov",
                        "bitrate" : 143,
                        "codec" : "mpeg4",
                        "resolution" : {
                            "w" : 672,
                            "h" : 504 },
                        "resolutionSquare" : {
                            "w" : 672,
                            "h" : 504 },
                        "rotate" : 0,
                        "fps" : 25,
                        "stream" : 0,
                        "aspectString" : "4:3",
                        "aspect" : 1.3333333333333333,
                        "pixelString" : "1:1",
                        "pixel" : 1 },
                    "audio" : {
                        "codec" : "",
                        "bitrate" : 0,
                        "sample_rate" : 0,
                        "stream" : 0 },
                    "file" : "./videos/SMPTE_Color_Bars_04.mp4",
                    "stat" : {
                        "dev" : 2053,
                        "mode" : 33204,
                        "nlink" : 1,
                        "uid" : 1000,
                        "gid" : 1000,
                        "rdev" : 0,
                        "blksize" : 4096,
                        "ino" : 3527,
                        "size" : 32325338,
                        "blocks" : 63144,
                        "atime" : "2013-04-16T15:36:10.000Z",
                        "mtime" : "2013-04-16T15:42:31.000Z",
                        "ctime" : "2013-04-16T15:42:31.000Z",
                        "name" : "SMPTE_Color_Bars_04.mp4",
                        "type" : "file" },
                    "checksum" : "ce96533228445a761ebadb396adbf053",
                    "name" : "",
                    "template" : "mediaview",
                    "notes" : "",
                    "trim" : {
                        "timein" : 0,
                        "timeout" : 0 },
                    "overlay" : [ ],
                    "starts" : 0,
                    "ends" : 0 } ],
            "models" : [
                {
                    "ffmpegversion" : "1.2",
                    "title" : "",
                    "artist" : "",
                    "album" : "",
                    "track" : "",
                    "date" : "",
                    "durationraw" : "00:30:00.00",
                    "durationsec" : 1800,
                    "synched" : true,
                    "video" : {
                        "container" : "mov",
                        "bitrate" : 143,
                        "codec" : "mpeg4",
                        "resolution" : {
                            "w" : 672,
                            "h" : 504 },
                        "resolutionSquare" : {
                            "w" : 672,
                            "h" : 504 },
                        "rotate" : 0,
                        "fps" : 25,
                        "stream" : 0,
                        "aspectString" : "4:3",
                        "aspect" : 1.3333333333333333,
                        "pixelString" : "1:1",
                        "pixel" : 1 },
                    "audio" : {
                        "codec" : "",
                        "bitrate" : 0,
                        "sample_rate" : 0,
                        "stream" : 0 },
                    "file" : "./videos/SMPTE_Color_Bars_04.mp4",
                    "stat" : {
                        "dev" : 2053,
                        "mode" : 33204,
                        "nlink" : 1,
                        "uid" : 1000,
                        "gid" : 1000,
                        "rdev" : 0,
                        "blksize" : 4096,
                        "ino" : 3527,
                        "size" : 32325338,
                        "blocks" : 63144,
                        "atime" : "2013-04-16T15:36:10.000Z",
                        "mtime" : "2013-04-16T15:42:31.000Z",
                        "ctime" : "2013-04-16T15:42:31.000Z",
                        "name" : "SMPTE_Color_Bars_04.mp4",
                        "type" : "file" },
                    "checksum" : "ce96533228445a761ebadb396adbf053",
                    "name" : "",
                    "template" : "mediaview",
                    "notes" : "",
                    "trim" : {
                        "timein" : 0,
                        "timeout" : 0 },
                    "overlay" : [ ],
                    "starts" : 0,
                    "ends" : 0 },
                {
                    "ffmpegversion" : "1.2",
                    "title" : "",
                    "artist" : "",
                    "album" : "",
                    "track" : "",
                    "date" : "",
                    "durationraw" : "00:30:00.00",
                    "durationsec" : 1800,
                    "synched" : true,
                    "video" : {
                        "container" : "mov",
                        "bitrate" : 143,
                        "codec" : "mpeg4",
                        "resolution" : {
                            "w" : 672,
                            "h" : 504 },
                        "resolutionSquare" : {
                            "w" : 672,
                            "h" : 504 },
                        "rotate" : 0,
                        "fps" : 25,
                        "stream" : 0,
                        "aspectString" : "4:3",
                        "aspect" : 1.3333333333333333,
                        "pixelString" : "1:1",
                        "pixel" : 1 },
                    "audio" : {
                        "codec" : "",
                        "bitrate" : 0,
                        "sample_rate" : 0,
                        "stream" : 0 },
                    "file" : "./videos/SMPTE_Color_Bars_04.mp4",
                    "stat" : {
                        "dev" : 2053,
                        "mode" : 33204,
                        "nlink" : 1,
                        "uid" : 1000,
                        "gid" : 1000,
                        "rdev" : 0,
                        "blksize" : 4096,
                        "ino" : 3527,
                        "size" : 32325338,
                        "blocks" : 63144,
                        "atime" : "2013-04-16T15:36:10.000Z",
                        "mtime" : "2013-04-16T15:42:31.000Z",
                        "ctime" : "2013-04-16T15:42:31.000Z",
                        "name" : "SMPTE_Color_Bars_04.mp4",
                        "type" : "file" },
                    "checksum" : "ce96533228445a761ebadb396adbf053",
                    "name" : "",
                    "template" : "mediaview",
                    "notes" : "",
                    "trim" : {
                        "timein" : 0,
                        "timeout" : 0 },
                    "overlay" : [ ],
                    "starts" : 0,
                    "ends" : 0 } ],
            "name" : "1h",
            "fixed" : false,
            "duration" : 3600000,
            "pos" : 0,
            "_id" : "516d72f773de5c8854000002"
        }
    ]
}